pyclustering: pyclustering.nnet.fsync.fsync_dynamic Class Reference
pyclustering.nnet.fsync.fsync_dynamic Class Reference
Represents output dynamic of Sync in frequency domain.
Public Member Functions
def __init__ (self, amplitude, time)
Constructor of Sync dynamic in frequency domain.
def output (self)
(list) Returns output dynamic of the Sync network (amplitudes of each oscillator in the network) during simulation.
def time (self)
(list) Returns time-points corresponds to dynamic-points points.
def __len__ (self)
(uint) Returns number of simulation steps that are stored in dynamic.
def __getitem__ (self, index)
Indexing of the dynamic.
def allocate_sync_ensembles (self, tolerance=0.1)
Allocate clusters in line with ensembles of synchronous oscillators where each synchronous ensemble corresponds to only one cluster.
def extract_number_oscillations (self, index, amplitude_threshold)
Extracts number of oscillations of specified oscillator.
Detailed Description
Represents output dynamic of Sync in frequency domain.
Definition at line 22 of file fsync.py.
Constructor & Destructor Documentation
__init__()
def pyclustering.nnet.fsync.fsync_dynamic.__init__ (self, amplitude, time)
Constructor of Sync dynamic in frequency domain.
Parameters
[in] amplitude (list): Dynamic of oscillators on each step of simulation.
[in] time (list): Simulation time where each time-point corresponds to amplitude-point.
Definition at line 29 of file fsync.py.
Member Function Documentation
allocate_sync_ensembles()
def pyclustering.nnet.fsync.fsync_dynamic.allocate_sync_ensembles (self, tolerance = 0.1)
Allocate clusters in line with ensembles of synchronous oscillators where each synchronous ensemble corresponds to only one cluster.
Parameters
[in] tolerance (double): Maximum error for allocation of synchronous ensemble oscillators.
Returns
(list) Grours of indexes of synchronous oscillators, for example, [ [index_osc1, index_osc3], [index_osc2], [index_osc4, index_osc5] ].
Definition at line 86 of file fsync.py.
Referenced by pyclustering.gcolor.hysteresis.hysteresis_analyser.allocate_clusters(), pyclustering.cluster.syncnet.syncnet_analyser.allocate_clusters(), and pyclustering.gcolor.sync.syncgcolor_analyser.allocate_color_clusters().
extract_number_oscillations()
def pyclustering.nnet.fsync.fsync_dynamic.extract_number_oscillations (self, index, amplitude_threshold)
Extracts number of oscillations of specified oscillator.
Parameters
[in] index (uint): Index of oscillator whose dynamic is considered.
[in] amplitude_threshold (double): Amplitude threshold when oscillation is taken into account, for example, when oscillator amplitude is greater than threshold then oscillation is incremented.
Returns
(uint) Number of oscillations of specified oscillator.
Definition at line 99 of file fsync.py.
The documentation for this class was generated from the following file:
pyclustering/nnet/fsync.py