theme: jekyll-theme-cayman
title: PyClustering Library
description: Python, C++ data mining (clustering, oscillatory networks, neural networks, etc.) library
github:
  repository_url: https://github.com/annoviko/pyclustering
