theme: jekyll-theme-architect
title: pyclustering
description: Python, C++ data mining library
show_downloads: true
google_analytics: UA-122464132-1
github:
  owner_name: annoviko
  owner_url: https://github.com/annoviko
  repository_url: https://github.com/annoviko/pyclustering
  repository_nwo: annoviko/pyclustering
  repository_name: pyclustering library
  clone_url: https://github.com/annoviko/pyclustering.git
  releases_url: https://github.com/annoviko/pyclustering/releases
  issues_url: https://github.com/annoviko/pyclustering/issues
  zip_url: https://github.com/annoviko/pyclustering/releases/download/0.9.1/pyclustering-0.9.1-binaries-all.tar.gz
  tar_url: https://github.com/annoviko/pyclustering/releases/download/0.9.1/pyclustering-0.9.1-binaries-all.tar.gz
  is_user_page: false
  is_project_page: true
