theme: jekyll-theme-architect
title: pyclustering
description: Python, C++ data mining (clustering, oscillatory networks, neural networks, etc.) library
show_downloads: true
github:
  owner_name: annoviko
  owner_url: https://github.com/annoviko
  repository_url: https://github.com/annoviko/pyclustering
  repository_nwo: annoviko/pyclustering
  repository_name: pyclustering library
  clone_url: https://github.com/annoviko/pyclustering.git
  releases_url: https://github.com/annoviko/pyclustering/releases
  issues_url: https://github.com/annoviko/pyclustering/issues
  tar_url: https://files.pythonhosted.org/packages/45/e2/e5b3cd92fb6dbb6539bdacbbf88593b93e728eb8ea3b832f137dc591709c/pyclustering-0.8.1.tar.gz
  is_user_page: false
  is_project_page: true
