pyclustering.container.cftree.non_leaf_node Class Reference
pyclustering.container.cftree.non_leaf_node Class Reference
Representation of clustering feature non-leaf node.
Public Member Functions
def successors (self)
def __init__ (self, feature, parent, successors, payload)
Create CF Non-leaf node.
def __repr__ (self)
def __str__ (self)
def insert_successor (self, successor)
Insert successor to the node.
def remove_successor (self, successor)
Remove successor from the node.
def merge (self, node)
Merge non-leaf node to the current.
def get_farthest_successors (self, type_measurement)
Find pair of farthest successors of the node in line with measurement type.
def get_nearest_successors (self, type_measurement)
Find pair of nearest successors of the node in line with measurement type.
Public Member Functions inherited from pyclustering.container.cftree.cfnode
def __init__ (self, feature, parent, payload)
Constructor of abstract CF node.
def __repr__ (self)
def __str__ (self)
def get_distance (self, node, type_measurement)
Calculates distance between nodes in line with specified type measurement.
Public Attributes
type
Node type in CF tree that is CFNODE_NONLEAF for non leaf node.
Public Attributes inherited from pyclustering.container.cftree.cfnode
feature
Clustering feature of the node.
parent
Pointer to the parent node (None for root).
type
Type node (leaf or non-leaf).
payload
Payload of node where user data can be stored.
Detailed Description
Representation of clustering feature non-leaf node.
Definition at line 446 of file cftree.py.
Constructor & Destructor Documentation
__init__()
def pyclustering.container.cftree.non_leaf_node.__init__ (self, feature, parent, successors, payload)
Create CF Non-leaf node.
Parameters
[in] feature (cfentry): Clustering feature of the created node.
[in] parent (non_leaf_node): Parent of the created node.
[in] successors (list): List of successors of the node.
[in] payload (*): Data that is stored by the node.
Definition at line 461 of file cftree.py.
Member Function Documentation
__repr__()
def pyclustering.container.cftree.non_leaf_node.__repr__ (self)
Returns
(string) Representation of non-leaf node representation.
Definition at line 480 of file cftree.py.
Referenced by pyclustering.container.kdtree.node.__str__().
__str__()
def pyclustering.container.cftree.non_leaf_node.__str__ (self)
Returns
(string) String non-leaf representation.
Definition at line 488 of file cftree.py.
get_farthest_successors()
def pyclustering.container.cftree.non_leaf_node.get_farthest_successors (self, type_measurement)
Find pair of farthest successors of the node in line with measurement type.
Parameters
[in] type_measurement (measurement_type): Measurement type that is used for obtaining farthest successors.
Returns
(list) Pair of farthest successors represented by list [cfnode1, cfnode2].
Definition at line 539 of file cftree.py.
get_nearest_successors()
def pyclustering.container.cftree.non_leaf_node.get_nearest_successors (self, type_measurement)
Find pair of nearest successors of the node in line with measurement type.
Parameters
[in] type_measurement (measurement_type): Measurement type that is used for obtaining nearest successors.
Returns
(list) Pair of nearest successors represented by list.
Definition at line 568 of file cftree.py.
insert_successor()
def pyclustering.container.cftree.non_leaf_node.insert_successor (self, successor)
Insert successor to the node.
Parameters
[in] successor (cfnode): Successor for adding.
Definition at line 496 of file cftree.py.
merge()
def pyclustering.container.cftree.non_leaf_node.merge (self, node)
Merge non-leaf node to the current.
Parameters
[in] node (non_leaf_node): Non-leaf node that should be merged with current.
Definition at line 524 of file cftree.py.
remove_successor()
def pyclustering.container.cftree.non_leaf_node.remove_successor (self, successor)
Remove successor from the node.
Parameters
[in] successor (cfnode): Successor for removing.
Definition at line 510 of file cftree.py.
successors()
def pyclustering.container.cftree.non_leaf_node.successors (self)
Returns
(list) List of successors of the node.
Definition at line 453 of file cftree.py.
Referenced by pyclustering.container.cftree.non_leaf_node.__repr__(), pyclustering.container.cftree.non_leaf_node.get_farthest_successors(), pyclustering.container.cftree.non_leaf_node.get_nearest_successors(), pyclustering.container.cftree.non_leaf_node.insert_successor(), pyclustering.container.cftree.non_leaf_node.merge(), and pyclustering.container.cftree.non_leaf_node.remove_successor().
Member Data Documentation
type
pyclustering.container.cftree.non_leaf_node.type
Node type in CF tree that is CFNODE_NONLEAF for non leaf node.
Definition at line 475 of file cftree.py.
The documentation for this class was generated from the following file:
pyclustering/container/cftree.py