pyclustering: pyclustering.nnet.network Class Reference
pyclustering.nnet.network Class Reference
Common network description that consists of information about oscillators and connection between them.
Public Member Functions
def height (self)
Height of the network grid (that is defined by amout of oscillators in each column), this value is zero in case of non-grid structure.
def width (self)
Width of the network grid, this value is zero in case of non-grid structure.
def structure (self)
Type of network structure that is used for connecting oscillators.
def __init__ (self, num_osc, type_conn=conn_type.ALL_TO_ALL, conn_repr=conn_represent.MATRIX, height=None, width=None)
Constructor of the network.
def __len__ (self)
Returns size of the network that is defined by amount of oscillators.
def has_connection (self, i, j)
Returns True if there is connection between i and j oscillators and False - if connection doesn't exist.
def set_connection (self, i, j)
Couples two specified oscillators in the network with dynamic connections.
def get_neighbors (self, index)
Finds neighbors of the oscillator with specified index.
Detailed Description
Common network description that consists of information about oscillators and connection between them.
Definition at line 82 of file __init__.py.
Constructor & Destructor Documentation
__init__()
def pyclustering.nnet.network.__init__ (self, num_osc, type_conn = conn_type.ALL_TO_ALL, conn_repr = conn_represent.MATRIX, height = None, width = None)
Constructor of the network.
Parameters
[in] num_osc (uint): Number of oscillators in the network that defines size of the network.
[in] type_conn (conn_type): Type of connections that are used in the network between oscillators.
[in] conn_repr (conn_represent): Type of representation of connections.
[in] height (uint): Number of oscillators in column of the network, this argument is used only for network with grid structure (GRID_FOUR, GRID_EIGHT), for other types this argument is ignored.
[in] width (uint): Number of oscillotors in row of the network, this argument is used only for network with grid structure (GRID_FOUR, GRID_EIGHT), for other types this argument is ignored.
Reimplemented in pyclustering.nnet.legion.legion_network, and pyclustering.nnet.hysteresis.hysteresis_network.
Definition at line 129 of file __init__.py.
Member Function Documentation
get_neighbors()
def pyclustering.nnet.network.get_neighbors (self, index)
Finds neighbors of the oscillator with specified index.
Parameters
[in] index (uint): index of oscillator for which neighbors should be found in the network.
Returns
(list) Indexes of neighbors of the specified oscillator.
Reimplemented in pyclustering.nnet.sync.sync_network.
Definition at line 394 of file __init__.py.
Referenced by pyclustering.nnet.legion.legion_network.__len__(), pyclustering.cluster.syncnet.syncnet.process(), pyclustering.cluster.syncnet.syncnet.show_network(), pyclustering.nnet.legion.legion_network.simulate(), and pyclustering.nnet.pcnn.pcnn_network.simulate().
has_connection()
def pyclustering.nnet.network.has_connection (self, i, j)
Returns True if there is connection between i and j oscillators and False - if connection doesn't exist.
Parameters
[in] i (uint): index of an oscillator in the network.
[in] j (uint): index of an oscillator in the network.
Reimplemented in pyclustering.nnet.sync.sync_network.
Definition at line 351 of file __init__.py.
Referenced by pyclustering.gcolor.sync.syncgcolor.__init__(), pyclustering.nnet.hysteresis.hysteresis_network.__init__(), pyclustering.cluster.syncnet.syncnet.show_network(), pyclustering.nnet.fsync.fsync_network.simulate(), and pyclustering.nnet.sync.sync_network.sync_local_order().
height()
def pyclustering.nnet.network.height (self)
Height of the network grid (that is defined by amout of oscillators in each column), this value is zero in case of non-grid structure.
Note
This property returns valid value only for network with grid structure.
Definition at line 99 of file __init__.py.
set_connection()
def pyclustering.nnet.network.set_connection (self, i, j)
Couples two specified oscillators in the network with dynamic connections.
Parameters
[in] i (uint): index of an oscillator that should be coupled with oscillator 'j' in the network.
[in] j (uint): index of an oscillator that should be coupled with oscillator 'i' in the network.
Note
This method can be used only in case of DYNAMIC connections, otherwise it throws expection.
Definition at line 372 of file __init__.py.
Referenced by pyclustering.cluster.syncnet.syncnet.__del__(), and pyclustering.gcolor.sync.syncgcolor.__init__().
width()
def pyclustering.nnet.network.width (self)
Width of the network grid, this value is zero in case of non-grid structure.
Note
This property returns valid value only for network with grid structure.
Definition at line 110 of file __init__.py.
The documentation for this class was generated from the following file:
pyclustering/nnet/__init__.py