pyclustering.nnet.hysteresis.hysteresis_dynamic Class Reference
pyclustering.nnet.hysteresis.hysteresis_dynamic Class Reference
Represents output dynamic of hysteresis oscillatory network.
Public Member Functions
def output (self)
(list) Returns outputs of oscillator during simulation.
def time (self)
(list) Returns sampling times when dynamic is measured during simulation.
def __init__ (self, amplitudes, time)
Constructor of hysteresis neural network dynamic.
def __len__ (self)
(uint) Returns number of simulation steps that are stored in dynamic.
def allocate_sync_ensembles (self, tolerance=0.1, threshold_steps=1)
Allocate clusters in line with ensembles of synchronous oscillators where each synchronous ensemble corresponds to only one cluster.
Detailed Description
Represents output dynamic of hysteresis oscillatory network.
Definition at line 36 of file hysteresis.py.
Constructor & Destructor Documentation
__init__()
def pyclustering.nnet.hysteresis.hysteresis_dynamic.__init__ (self, amplitudes, time)
Constructor of hysteresis neural network dynamic.
Parameters
[in] amplitudes (list): Dynamic (amplitudes) of oscillators on each step of simulation.
[in] time (list): Simulation time (timestamps of simulation steps) when amplitudes are stored.
Definition at line 61 of file hysteresis.py.
Member Function Documentation
allocate_sync_ensembles()
def pyclustering.nnet.hysteresis.hysteresis_dynamic.allocate_sync_ensembles (self, tolerance = 0.1, threshold_steps = 1)
Allocate clusters in line with ensembles of synchronous oscillators where each synchronous ensemble corresponds to only one cluster.
Parameters
[in] tolerance (double): Maximum error for allocation of synchronous ensemble oscillators.
[in] threshold_steps (uint): Number of steps from the end of simulation that should be analysed for ensemble allocation. If amout of simulation steps has been less than threshold steps than amount of steps will be reduced to amout of simulation steps.
Returns
(list) Grours of indexes of synchronous oscillators, for example, [ [index_osc1, index_osc3], [index_osc2], [index_osc4, index_osc5] ]."
Definition at line 87 of file hysteresis.py.
Referenced by pyclustering.gcolor.hysteresis.hysteresis_analyser.allocate_clusters(), pyclustering.cluster.syncnet.syncnet_analyser.allocate_clusters(), and pyclustering.gcolor.sync.syncgcolor_analyser.allocate_color_clusters().
The documentation for this class was generated from the following file:
pyclustering/nnet/hysteresis.py